### PR TITLE
Don't set dark theme when installed

### PR DESCRIPTION
**Pull request by forivall**
Some of us prefer it light, and already have the theme set to light in the devtools options. It would probably be useful to just put a little screenshot / tutorial on the homepage, or add the setting to the addon settings page as well.

### CODE REVIEW

**Comment by nt1m** [comment]
@bgrins @canuckistani What do you think ?

**Comment by bgrins** [comment]
Having a screenshot showing how to change to dark / light theme sounds like a good idea.  Or do we already have a support article about this that we could link to?  Don't feel too strongly about the default here - seems it might be expected to switch to dark since that matches the DE default

**Comment by nt1m** [comment]
Closing as the devedition theme will be coming to release as 2 separate compact themes (light & dark)

**Comment by nt1m** [comment]
Which means this add-on will be deprecated.

**Pull request closed without merging**
